# Header
menu:
  首页: /
  新闻动态: /archives
  研究团队: /yjtd
  研究方向: /yjfx
  研究成果: /yjcg
  项目支持: /xmzc
  招生信息: /zsxx
  # 关于: /about

# Content
excerpt_link: 阅读全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /images/favicon.ico
webclip: /images/webclip
brand:   /images/wit-title.png

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/banner.jpg
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: 复杂系统与智能控制
  secondary: 先进控制与智能自动化的理论、技术与应用
  archives: 汇聚热点话题 打造创新思路
  pages: 复杂系统与智能控制实验室
  posts: 实践见真知

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js